Added image table detector annotator
JohnSnowLabs/nlu pull request #221
Opened 2023-11-15 21:39 UTC by gadde5300

Hi @C-K-Loan ,
I have disabled the light pipeline in this pr as it wasnt working with it enabled.

2023-11-28 02:39 UTC, gadde5300 commented
Added a new light pipeline feature to the component universe.

2023-12-05 00:26 UTC, C-K-Loan requested changes

2023-12-05 00:26 UTC, C-K-Loan commented on nlu/pipe/utils/predict_helper.py
> +            pipe.__configure_light_pipe_usage__(DataConversionUtils.size_of(data), multithread)
I think this should be if pipe.is_light_pipe_incompatible  and not isinstance()

2023-12-05 00:26 UTC, C-K-Loan commented on nlu/pipe/pipeline.py
> +                if isinstance(self.is_light_pipe_incompatible,()):
if self.is_light_pipe_incompatible instead of instance

2023-12-05 00:26 UTC, C-K-Loan commented on nlu/universe/feature_node_universes.py
>          # TODO OUPUT!! REGION or TABLE??? IS IT THE SAME???
Remove commments

2023-12-05 00:26 UTC, C-K-Loan commented on nlu/pipe/extractors/extractor_methods/ocr_extractors.py
>      df = df.withColumn("table_index", df.ocr_table.area.index)
Can you check if this has any effect on the existing table extractor?

2023-12-13 01:15 UTC, merged